server:
  port: 8989
eureka:
  instance:
    hostname: localhost
spring:
      
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - OPTIONS
        
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/passenger/**  
        - id: train-service
          uri: lb://train-service
          predicates:
            - Path=/train/** 
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/** 
 
          