server:
  port: 8989
euraka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/**
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/passenger/**  
        - id: train-service
          uri: lb://train-service
          predicates:
            - Path=/train/** 
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/** 
          